//a dummy data for the feed which consits of the user's name, the user's profile picture, the post image, the post description, the number of likes, the number of comments, and the number of shares
export const postData = [
  {
    id: '100',
    name: 'Ram Charan',
    profilePic: 'https://randomuser.me/api/portraits',
    postImage: 'https://source.unsplash.com/random',
    title:'This is a post title',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    likes: 123,
    comments: 12,
    shares: 44,
    answers: [
      {
        id: '1001',
        name: 'Allu Arjun',
        profilePic: 'https://randomuser.me/api/portraits',
        postImage: 'https://source.unsplash.com/random',
        title:'This one is the right answer', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        likes: 123,
        comments: 12,
        shares: 44,
      },
      {
        id: '1002',
        name: 'Allu Arjun',
        profilePic: 'https://randomuser.me/api/portraits',
        postImage: 'https://source.unsplash.com/random',
        title:'This one is the right answer', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        likes: 123,
        comments: 12,
        shares: 44,
      },
      {
        id: '1003',
        name: 'Allu Arjun',
        profilePic: 'https://randomuser.me/api/portraits',
        postImage: 'https://source.unsplash.com/random',
        title:'This one is the right answer', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        likes: 123,
        comments: 12,
        shares: 44,
      },
    ]
    },

    {
    id: '101', 
    name: 'Ram Charan',
    profilePic: 'https://randomuser.me/api/portraits',
    postImage: 'https://source.unsplash.com/random',
    title:'This is a post description',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    likes: 123,
    comments: 12,
    shares: 44,
    answers: [
      {
        id: '1011',
        name: 'Allu Arjun',
        profilePic: 'https://randomuser.me/api/portraits',
        postImage: 'https://source.unsplash.com/random',
        title:'This one is the right answer', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        likes: 123,
        comments: 12,
        shares: 44,
      },
      {
        id: '1012',
        name: 'Allu Arjun',
        profilePic: 'https://randomuser.me/api/portraits',
        postImage: 'https://source.unsplash.com/random',
        title:'This one is the right answer', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        likes: 123,
        comments: 12,
        shares: 44,
      },
      {
        id: '1013',
        name: 'Allu Arjun',
        profilePic: 'https://randomuser.me/api/portraits',
        postImage: 'https://source.unsplash.com/random',
        title:'This one is the right answer', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book',
        likes: 123,
        comments: 12,
        shares: 44,
    },
    ]
    },


    {
    id: '102',
    name: 'Ram Charan',
    profilePic: 'https://randomuser.me/api/portraits',
    postImage: 'https://source.unsplash.com/random',
    title:'This is a post title',
    description: 'This is a post description',
    likes: 123,
    comments: 12,
    shares: 44,
    answers: [
      {
        id: '1021',
        name: 'Allu Arjun',
        profilePic: 'https://randomuser.me/api/portraits',
        postImage: 'https://source.unsplash.com/random',
        title:'This one is the right answer', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        likes: 123,
        comments: 12,
        shares: 44,
      },
      {
        id: '1022',
        name: 'Allu Arjun',
        profilePic: 'https://randomuser.me/api/portraits',
        postImage: 'https://source.unsplash.com/random',
        title:'This one is the right answer', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        likes: 123,
        comments: 12,
        shares: 44,
      },
      {
        id: '1023',
        name: 'Allu Arjun',
        profilePic: 'https://randomuser.me/api/portraits',
        postImage: 'https://source.unsplash.com/random',
        title:'This one is the right answer', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        likes: 123,
        comments: 12,
        shares: 44,
      },
    ]
    },

    {
    id: '103',
    name: 'Ram Charan',
    profilePic: 'https://randomuser.me/api/portraits',
    postImage: 'https://source.unsplash.com/random',
    title:'This is a post title',
    description: 'This is a post description',
    likes: 123,
    comments: 12,
    shares: 44,
    answers: [
      {
        id: '1031',
        name: 'Allu Arjun',
        profilePic: 'https://randomuser.me/api/portraits',
        postImage: 'https://source.unsplash.com/random',
        title:'This one is the right answer', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        likes: 123,
        comments: 12,
        shares: 44,
      },
      {
        id: '1032',
        name: 'Allu Arjun',
        profilePic: 'https://randomuser.me/api/portraits',
        postImage: 'https://source.unsplash.com/random',
        title:'This one is the right answer', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        likes: 123,
        comments: 12,
        shares: 44,
      },
      {
        id: '1033',
        name: 'Allu Arjun',
        profilePic: 'https://randomuser.me/api/portraits',
        postImage: 'https://source.unsplash.com/random',
        title:'This one is the right answer', 
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        likes: 123,
        comments: 12,
        shares: 44,
      },
    ]
    },
]

export const RecentPosts = [
  {
    title: 'This is a hot topic right now.',
    image: 'https://turk.net/blog/wp-content/uploads/Google-Bard-Nedir-ve-Nasil-Kullanilir-.jpg',
    points: 123,
    comments: 12,
    date: '2 days ago',
  },
  {
    title: 'This is a hot topic right now.',
    image: 'https://turk.net/blog/wp-content/uploads/Google-Bard-Nedir-ve-Nasil-Kullanilir-.jpg',
    points: 123,
    comments: 12,
    date: '2 days ago',
  },
  {
    title: 'This is a hot topic right now.',
    image: 'https://turk.net/blog/wp-content/uploads/Google-Bard-Nedir-ve-Nasil-Kullanilir-.jpg',
    points: 123,
    comments: 12,
    date: '2 days ago',
  },
  {
    title: 'This is a hot topic right now.',
    image: 'https://turk.net/blog/wp-content/uploads/Google-Bard-Nedir-ve-Nasil-Kullanilir-.jpg',
    points: 123,
    comments: 12,
    date: '2 days ago',
  },
  {
    title: 'This is a hot topic right now.',
    image: 'https://turk.net/blog/wp-content/uploads/Google-Bard-Nedir-ve-Nasil-Kullanilir-.jpg',
    points: 123,
    comments: 12,
    date: '2 days ago',
  },
]